name: CrystalCavernsPortal
version: '${project.version}'
main: cc.crystalcavernsportal.CrystalCavernsPortal
api-version: 1.19
depend: [CommandPanels]
commands:
  profile:
    description: Used to open a player's profile.