name: CrystalCavernsPortal
version: '1.0'
main: cc.crystalcavernsportal.CrystalCavernsPortal
api-version: 1.19
depend: [CommandPanels]
commands:
  realm:
    description: Used for internal processes.
    permission: crystalcaverns.realm
  spawn:
    description: Teleports the player to the server's global spawn point.
    aliases: [lobby, hub]